version: '3'

services:
  eaas_e2e_tfn_mock_dev:
    container_name: eaas_e2e_tfn_mock_dev
    build:
      context: .
    working_dir: /extension
    command: cextrun -d -n
    volumes: 
      - .:/extension
    env_file:
      - .eaas_e2e_tfn_mock_dev.env

  eaas_e2e_tfn_mock_bash:
    container_name: eaas_e2e_tfn_mock_bash
    build:
      context: .
    working_dir: /extension
    command: /bin/bash
    stdin_open: true
    tty: true
    volumes:
      - .:/extension
    env_file:
      - .eaas_e2e_tfn_mock_dev.env

  eaas_e2e_tfn_mock_test:
    container_name: eaas_e2e_tfn_mock_test
    build:
      context: .
    working_dir: /extension
    command: extension-test
    volumes:
      - .:/extension
    env_file:
      - .eaas_e2e_tfn_mock_dev.env
